# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf390edb4ba9b01da27891c97ee23df150b448534d0f6d14e8270d51d521bcbe9d98f9dd423413c194ae4d263a249e5c4b590f48ab1a8b309388af561f9ea44d

test:
  secret_key_base: 05530dcb737655bac9a27b8d13978e7f0e8eab6359b1cdb998a6acc789214de2739eadd1607b516ed3c82e6b98739a54d0395a08827442cdf10230f1347f1ddb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
